### ISSUE TITLE
Error on cargo build-bpf

### ISSUE THREAD

**Issue by harrisonmount** [tracy-codes/solana-nft-staking-program#5]
could not compile `staking-nft-contract` due to previous error, 

Seems to be from a linking issue:
linking with `\\?\C:\Users\myname\.local\share\solana\install\releases\stable-de065d865a08dea8eea289fd276423a720f8744c\solana-release\bin\sdk\bpf\dependencies\bpf-tools\llvm\bin\ld.lld` failed: exit code: 1

**Comment by tracy-codes** [comment]
This sounds like a local system configuration issue. This program builds just fine on my system using the version of Solana that is defined in the program's Cargo.toml.

**Comment by harrisonmount** [comment]
Just had to update my solana version from 1.9.8 to most recent. 
Has anyone made an frontend UI say with react or similar?

Everything's working, will be donating soon.
